Suppressing warnings given by Xcode 15.
sindresorhus/Settings pull request #103
Opened 2023-06-08 02:04 UTC by ShikiSuen

* All `import Cocoa` are expected to be changed to `import AppKit` or `import UIKit` in order to be more platform-specific. Otherwise, Xcode 15 will give warnings.
* Use `NSApp.activate()` for macOS 14 Sonoma and later.

closing #102

2023-06-08 02:09 UTC, ShikiSuen commented
This PR needs further modification to deal with compilation errors happened on Xcode 14 and earlier.
I am running out of my idea how to deal with it.
Looks like the SDK availability check doesn't work well.

Lemme see whether Swift version checks would work.

<img width="1440" alt="image" src="https://github.com/sindresorhus/Settings/assets/3164826/0bc2f7b0-d1e0-4f50-adb3-6bc0a4d43561">

2023-06-08 02:13 UTC, ShikiSuen commented
Errors solved after adding compiler version check.

2023-06-09 11:17 UTC, sindresorhus requested changes

2023-06-09 11:17 UTC, sindresorhus commented on Sources/Settings/SettingsWindowController.swift
> +			NSApp.activate(ignoringOtherApps: true)
```suggestion
		NSApp.activate(ignoringOtherApps: true)
```

2023-06-09 11:17 UTC, sindresorhus commented on Sources/Settings/SettingsWindowController.swift
> +		#if compiler(>=5.9) && canImport(AppKit, _version: "14.0")
```suggestion
		#if compiler(>=5.9) && canImport(AppKit)
```

I don't think we need to check the AppKit version as the availability check already does that. And it's also marked as internal so I wouldn't want to rely on it.

2023-06-09 13:29 UTC, merged